### ISSUE TITLE
Celluloid backport warning

### ISSUE THREAD

**Issue by kylekyle** [kenichi/angelo#64]
When I run an angelo server, I get the warning

`
Celluloid 0.17.0 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
`

If I take the recommendation from the url and require `celluloid/current' before requiring `angelo`, angelo throws the following error:

```
/Users/kyle/.rvm/gems/ruby-2.2.3/gems/angelo-0.4.1/lib/angelo/server.rb:8:in `<class:Server>': uninitialized constant Celluloid::Logger (NameError)
	from /Users/kyle/.rvm/gems/ruby-2.2.3/gems/angelo-0.4.1/lib/angelo/server.rb:6:in `<module:Angelo>'
	from /Users/kyle/.rvm/gems/ruby-2.2.3/gems/angelo-0.4.1/lib/angelo/server.rb:4:in `<top (required)>'
	from /Users/kyle/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/kyle/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/kyle/.rvm/gems/ruby-2.2.3/gems/angelo-0.4.1/lib/angelo.rb:132:in `<top (required)>'
	from /Users/kyle/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /Users/kyle/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /Users/kyle/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from angelo.rb:2:in `<main>'
```

**Comment by kenichi** [comment]
as of 0.5.0, it should work to require celluloid/current above, thanks to #58. however, the actual issue is in how reel requires celluloid. you can see this same warning by requiring reel from the latest code. please let me know/reopen if that workaround does not work for you with 0.5.0 and i will see what i can do to get reel requiring the latest celluloid in a less noisy fashion.
